from __future__ import annotations

import argparse
import logging
from pathlib import Path

import pandas as pd

from .common import ensure_dir, pct_change, write_csv

LOGGER = logging.getLogger(__name__)


def analyse_treatment(
    indicators_dir: Path | str = "data/indicators",
    output_dir: Path | str = "data/analysis/treatment",
) -> dict[str, Path]:
    """
    Summarise WHO treatment cohorts generated by the indicators layer.

    Expected file:
      treatment_cohorts.csv

    This module does not infer outcome definitions. It works from fields already
    created by src/indicators/treatment.py.
    """
    indicators_dir = Path(indicators_dir)
    output_dir = ensure_dir(output_dir)
    path = indicators_dir / "treatment_cohorts.csv"

    if not path.exists():
        LOGGER.warning("Treatment cohort file not found: %s", path)
        return {}

    df = pd.read_csv(path, low_memory=False)
    if df.empty:
        return {}

    if "year" in df.columns:
        df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")

    metric_candidates = [
        "treatment_success_rate",
        "death_rate",
        "lost_to_followup_rate",
        "failure_rate",
        "not_evaluated_rate",
        "cohort_size",
        "successful_treatment",
        "died",
        "lost_to_followup",
        "failed",
        "not_evaluated",
    ]
    metrics = [c for c in metric_candidates if c in df.columns]

    group_keys = [c for c in ["cohort", "treatment_group", "category"] if c in df.columns]
    if not group_keys:
        df["_group"] = "all_treatment_cohorts"
        group_keys = ["_group"]

    summaries = []
    for keys, group in df.groupby(group_keys, dropna=False):
        if not isinstance(keys, tuple):
            keys = (keys,)
        base = dict(zip(group_keys, keys))
        group = group.sort_values("year") if "year" in group.columns else group

        for metric in metrics:
            valid = pd.to_numeric(group[metric], errors="coerce").dropna()
            if valid.empty:
                continue
            record = dict(base)
            record.update({
                "metric": metric,
                "first_value": float(valid.iloc[0]),
                "latest_value": float(valid.iloc[-1]),
                "absolute_change": float(valid.iloc[-1] - valid.iloc[0]),
                "percent_change": pct_change(valid),
                "observations": int(len(valid)),
            })
            if "year" in group.columns:
                aligned = group.loc[pd.to_numeric(group[metric], errors="coerce").notna()]
                record["first_year"] = int(aligned["year"].iloc[0])
                record["latest_year"] = int(aligned["year"].iloc[-1])
            summaries.append(record)

    summary = pd.DataFrame(summaries)

    series_path = output_dir / "treatment_series.csv"
    write_csv(
        df.drop(columns=["_group"], errors="ignore"),
        series_path,
        metadata={"grain": "treatment cohort-year where available"},
    )

    summary_path = output_dir / "treatment_trend_summary.csv"
    write_csv(
        summary,
        summary_path,
        metadata={
            "description": "Long-run treatment cohort metric changes.",
        },
    )

    return {"series": series_path, "summary": summary_path}


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyse TB treatment outcomes.")
    parser.add_argument("--indicators-dir", default="data/indicators")
    parser.add_argument("--output-dir", default="data/analysis/treatment")
    args = parser.parse_args()
    analyse_treatment(args.indicators_dir, args.output_dir)


if __name__ == "__main__":
    main()
